### ISSUE TITLE
[FEATURE] Function names

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#28]
* **What are you trying to do?**

The function names have become a bit messy. We currently have:

 * `audit_deps()` in v0.0.3
 * `audit_pkgs()`,  `audit_renv_lock()`,  `audit_req_txt()` in the dev branch.

The issues are:

 -  `audit_renv_lock()` and `audit_req_txt()` do exactly what you would expect
 - `audit_pkgs()` expects a vector of packages
 - `audit_deps()` is really odd, as the `deps` are either all installed packages, or a tibble of passed packages

* **What feature or behaviour is this required for?**

It's confusing (well it confuses me)

* **How could we solve this issue? (Not knowing is okay!)**

Rename the functions! Now is the time to break/deprecate things ;) Here are some quick suggestions, please suggest improvements

  - `audit_renv_lock()` and `audit_req_txt()` - look good
 - `audit_proj()` - this would scan an RStudio project for dependencies. For example, if an R package, it would read the DESCRIPTION file, and/or an env file
 - `audit_installed_pkgs()` - formally `audit_deps()`
 - `audit_pkgs()`  - don't really like this name, but can't think of something better. Perhaps just a general `audit()`?

* **Anything else?**

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie / @JosiahParry

**Comment by JosiahParry** [comment]
Thanks for raising this, Colin.

Regarding the name `audit_deps()`, I think this is misleading because it doesn't actually look at dependencies of packages but rather just searches for the package itself.

Disambiguating `audit_deps()` makes sense. I agree that `audit_installed_pkgs()` should be it's own function. 

Regarding `audit_pkgs()`, what would you prefer to pass rather than a vector? I think accepting arguments as vectors provides the most flexibility. 

Alternate name `audit_libs()`? `audit()` is also fine as it's generally a catch all.
