### ISSUE TITLE
Dev: Licence at the top of each R file

### ISSUE THREAD

**Issue by csgillespie** [sonatype-nexus-community/oysteR#7]
Typically in R packages, the DESCRIPTION contains the licence/copyright and so the header isn't required. Your package has the Apache 2 in the DESCRIPTION, so is it needed for the files? 

Proviso: I know nothing about licences

**Comment by DarthHater** [comment]
For Apache it's not strictly necessary, they are of the opinion that just having one attached to the repo is enough. However, we tend to do it anyways so that:

- Copyright for authors is maintained, say you author a whole file, it's nice to show that you are an author of that particular work
- Say the file walks off into another repo via copy-pasta, the header has gone with it and now someone knows the original was at least licensed Apache
  - This latter point probably becomes more important in a repo that uses a potentially conflicting or incompatible license (dunno if that exists for Apache, but imagine copying GPL code into a project that doesn't want to be open sourced)

We can survive without it with Apache, but the benefits of attaching it seem to outweigh not attaching it. Would love anyone else's perspective!

**Comment by DarthHater** [comment]
@csgillespie I talked with our CTO about this, and the statement:

`the files really should have the header, the logic being if the file gets separated from the project, one could claim they didn’t know the license`

That was more or less my second point. I'd say let's add them, and go from there!

**Comment by csgillespie** [comment]
OK, I'll add them in the near future. One further note, when you install an R package I'm 99% sure that all comments are stripped from the R files ;)

**Comment by DarthHater** [comment]
Yeah, I figured, it only really matters for the source repo tho, in case you have driveby people grabbing stuff.
